#Tabuada de um número:
n4 = float (input ('Digite um número para calcularmos a tabuada dele: '))
m1 = n4 * 1
m2 = n4 * 2
m3 = n4 * 3
m4 = n4 * 4
m5 = n4 * 5
m6 = n4 * 6
m7 = n4 * 7
m8 = n4 * 8
m9 = n4 * 9
print ('1 x {} = {}' .format (n4,m1 ))
print ('2 x {} = {}' .format (n4,m2 ))
print ('3 x {} = {}' .format (n4,m3 ))
print ('4 x {} = {}' .format (n4,m4 ))
print ('5 x {} = {}' .format (n4,m5 ))
print ('6 x {} = {}' .format (n4,m6 ))
print ('7 x {} = {}' .format (n4,m7 ))
print ('8 x {} = {}' .format (n4,m8 ))
print ('9 x {} = {}' .format (n4,m9 ))
